# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rails-bootstrap-daterangepicker 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "rails-bootstrap-daterangepicker"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Antonio Schiavon"]
  s.date = "2018-05-25"
  s.description = "rails-bootstrap-daterangepicker"
  s.email = ["aschiavon91@gmail.com"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/daterangepicker.min.js",
    "app/assets/stylesheets/daterangepicker.min.css",
    "app/assets/stylesheets/daterangepicker.min.map",
    "lib/rails-bootstrap-daterangepicker.rb",
    "lib/rails-bootstrap-daterangepicker/engine.rb",
    "lib/rails-bootstrap-daterangepicker/version.rb",
    "rails-bootstrap-daterangepicker.gemspec"
  ]
  s.homepage = "http://github.com/aschiavon91/rails-bootstrap-daterangepicker"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "rails-bootstrap-daterangepicker"
end
