# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rails-bootstrap-daterangepicker 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "rails-bootstrap-daterangepicker"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Christoph Chilian"]
  s.date = "2014-05-26"
  s.description = "rails-bootstrap-daterangepicker"
  s.email = ["christoph@chilian.de"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/bootstrap-daterangepicker.js",
    "app/assets/javascripts/moment.js",
    "app/assets/stylesheets/bootstrap-daterangepicker-2.css",
    "app/assets/stylesheets/bootstrap-daterangepicker-3.css",
    "lib/rails-bootstrap-daterangepicker.rb",
    "lib/rails-bootstrap-daterangepicker/engine.rb",
    "lib/rails-bootstrap-daterangepicker/version.rb",
    "rails-bootstrap-daterangepicker.gemspec"
  ]
  s.homepage = "http://github.com/chilian/rails-bootstrap-daterangepicker"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "rails-bootstrap-daterangepicker"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rails>, ["< 5", ">= 3.2.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14"])
      s.add_development_dependency(%q<rspec-rails>, ["~> 2.14"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0"])
    else
      s.add_dependency(%q<rails>, ["< 5", ">= 3.2.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<rspec>, ["~> 2.14"])
      s.add_dependency(%q<rspec-rails>, ["~> 2.14"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<simplecov>, ["~> 0"])
    end
  else
    s.add_dependency(%q<rails>, ["< 5", ">= 3.2.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<rspec>, ["~> 2.14"])
    s.add_dependency(%q<rspec-rails>, ["~> 2.14"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<simplecov>, ["~> 0"])
  end
end

